timezone: Europe/Paris
kramdown:
  input: GFM
  hard_wrap: false
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"
