timezone: Europe/Paris
kramdown:
  input: GFM
  hard_wrap: false
permalink: pretty

# Poole Setup
title: "Les Flaneurs"
tagline: "Two Americans in Paris"
description: "Stories of life abroad."
url: http://www.lesflaneurs.net
baseurl: /
paginate: 5

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"
